"""add ADR 021 fields to user_credentials

Revision ID: 37f42b9bb151
Revises: 27c4e1c7f6d4
Create Date: 2026-08-20 10:04:50.613865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37f42b9bb151'
down_revision: Union[str, Sequence[str], None] = '27c4e1c7f6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_credentials', sa.Column('is_valid', sa.Boolean(), nullable=False))
    op.add_column('user_credentials', sa.Column('failed_attempts', sa.Integer(), nullable=False))
    op.add_column('user_credentials', sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_credentials', 'locked_until')
    op.drop_column('user_credentials', 'failed_attempts')
    op.drop_column('user_credentials', 'is_valid')
    # ### end Alembic commands ###
